name: "ci"

on:
  push:

jobs:
  run-all-test:
    runs-on: ubuntu-latest
    name: Run all test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build -t ccc - < ./Dockerfile
      - name: test
        run: |
          docker run -v --platform=linux/amd64 "${PWD}:/src" -w/src ccc make test
